# Generated by Django 2.1.5 on 2019-02-13 02:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('rank', models.CharField(blank=True, choices=[('ex+', "'EX'"), ('ex', 'EX'), ('a+++', 'A+++'), ('a++', 'A++'), ('a+', 'A+'), ('a', 'A'), ('a-', 'A-'), ('b+', 'B+'), ('b', 'B'), ('b-', 'B-'), ('c+', 'C+'), ('c', 'C'), ('c-', 'C-'), ('d+', 'D+'), ('d', 'D'), ('d-', 'D-'), ('e+', 'E+'), ('e', 'E')], default='e', max_length=4)),
                ('initial_cd', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSkillEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=80)),
                ('duration', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('turn_type', models.CharField(blank=True, choices=[('inst', 'Instant'), ('turn', 'Turn'), ('time', 'Time')], default='turn', max_length=4)),
                ('description', models.CharField(max_length=80)),
                ('level_1', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('level_2', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('level_3', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('level_4', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('level_5', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('level_6', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('level_7', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('level_8', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('level_9', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('level_10', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(default='Mash Kyrielight', max_length=80)),
                ('cost', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('atk_min', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('atk_max', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('atk_grail', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('hp_min', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('hp_max', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('hp_grail', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('attribute', models.CharField(blank=True, choices=[('m', 'Man'), ('e', 'Earth'), ('s', 'Sky'), ('t', 'Star'), ('b', 'Beast')], default='m', max_length=1)),
                ('va', models.CharField(blank=True, choices=[('a', 'Takahashi Rie')], default='a', max_length=1)),
                ('artist', models.CharField(blank=True, choices=[('a', 'Takeuchi Takashi')], default='a', max_length=1)),
                ('growth_curve', models.CharField(blank=True, choices=[('l', 'Linear'), ('s', 'S'), ('rs', 'Reverse S'), ('ss', 'Semi S'), ('srs', 'Semi Reverse S')], default='l', max_length=3)),
                ('star_absorption', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('star_generation', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('np_charge_atk', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('np_charge_def', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('death_rate', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('alignment', models.CharField(blank=True, choices=[('lg', 'Lawful ・ Good'), ('ln', 'Lawful ・ Neutral'), ('le', 'Lawful ・ Evil'), ('li', 'Lawful ・ Insane'), ('ls', 'Lawful ・ Summer'), ('ng', 'Neutral ・ Good'), ('tn', 'True Neutral'), ('ne', 'Neutral ・ Evil'), ('ns', 'Neutral ・ Summer'), ('cg', 'Chaotic ・ Good'), ('cn', 'Chaotic ・ Neutral'), ('ce', 'Chaotic ・ Evil'), ('ci', 'Chaotic ・ Insane'), ('cb', 'Chaotic ・ Bride'), ('cs', 'Chaotic ・ Summer'), ('jh', 'Lawful-Good (Jekyll)・Chaotic-Evil (Hyde)')], default='lg', max_length=2)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1)),
                ('skil_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.ActiveSkill')),
                ('skil_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.ActiveSkill')),
                ('skil_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.ActiveSkill')),
            ],
        ),
        migrations.AddField(
            model_name='activeskill',
            name='effect',
            field=models.ManyToManyField(to='app.ActiveSkillEffect'),
        ),
    ]
