# Generated by Django 2.1.5 on 2019-02-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level_2',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level_3',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level_4',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level_5',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level_6',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level_7',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level_8',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level_9',
        ),
    ]
