# Generated by Django 2.1.5 on 2019-02-13 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190212_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='skil_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.ActiveSkill'),
        ),
        migrations.AlterField(
            model_name='servant',
            name='skil_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.ActiveSkill'),
        ),
        migrations.AlterField(
            model_name='servant',
            name='skil_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.ActiveSkill'),
        ),
    ]
