# Generated by Django 2.1.5 on 2019-02-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190212_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeskilleffect',
            name='target',
            field=models.CharField(blank=True, choices=[('s', 'Self'), ('t', 'Target'), ('a', 'Ally'), ('p', 'Party'), ('e', 'Enemies')], default='turn', max_length=1),
        ),
    ]
