# Generated by Django 2.1.5 on 2019-02-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190212_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeskill',
            name='rank',
            field=models.CharField(blank=True, choices=[("'EX'", "'EX'"), ('EX', 'EX'), ('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E+', 'E+'), ('E', 'E')], default='e', max_length=4),
        ),
    ]
