# Generated by Django 2.1.5 on 2019-02-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190212_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeskilleffect',
            name='turn_type',
            field=models.CharField(blank=True, choices=[('Instant', 'Instant'), ('turn', 'Turn'), ('time', 'Time')], default='turn', max_length=7),
        ),
    ]
