# Generated by Django 2.1.5 on 2019-02-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190212_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeskilleffect',
            name='target',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Target', 'Target'), ('Ally', 'Ally'), ('Party', 'Party'), ('enemies', 'Enemies')], default='Self', max_length=7),
        ),
    ]
