# Generated by Django 2.1.5 on 2019-02-13 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190212_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='artist',
            field=models.CharField(blank=True, choices=[('a', 'Takeuchi Takashi'), ('b', 'Taiki')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='servant',
            name='death_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='servant',
            name='np_charge_atk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='servant',
            name='np_charge_def',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='servant',
            name='star_generation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='servant',
            name='va',
            field=models.CharField(blank=True, choices=[('a', 'Takahashi Rie'), ('b', 'Sakurai Takahiro')], default='a', max_length=1),
        ),
    ]
