# Generated by Django 2.1.5 on 2019-02-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190212_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='artist',
            field=models.CharField(blank=True, choices=[('a', 'Takeuchi Takashi'), ('b', 'Taiki'), ('d', 'Honjou Raita')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='servant',
            name='va',
            field=models.CharField(blank=True, choices=[('a', 'Takahashi Rie'), ('b', 'Sakurai Takahiro'), ('c', 'Namikawa Daisuke'), ('d', 'Yusa Kōji')], default='a', max_length=1),
        ),
    ]
